const DUMMY_HAIRCUTS = [
    { country: "Thailand", city: "Bangkok", price: 250, currency: "THB", rating: 5, comment: "Amazing fade for the price!", date: "2025-11-20" },
    { country: "United States", city: "New York", price: 45, currency: "USD", rating: 4, comment: "Standard Brooklyn barbershop experience.", date: "2025-10-15" },
    { country: "United Kingdom", city: "London", price: 30, currency: "GBP", rating: 4, comment: "Solid scissor cut in Shoreditch.", date: "2025-12-05" },
    { country: "Germany", city: "Berlin", price: 25, currency: "EUR", rating: 3, comment: "Quick and clean, nothing fancy.", date: "2025-09-12" },
    { country: "Japan", city: "Tokyo", price: 4000, currency: "JPY", rating: 5, comment: "Incredible attention to detail. The hot towel was peak.", date: "2025-11-30" },
    { country: "Brazil", city: "Rio de Janeiro", price: 60, currency: "BRL", rating: 5, comment: "Best atmosphere ever. Football on the TV and great vibes.", date: "2025-08-22" },
    { country: "Australia", city: "Sydney", price: 55, currency: "AUD", rating: 4, comment: "Friendly staff, slightly expensive but worth it.", date: "2025-11-02" },
    { country: "South Africa", city: "Cape Town", price: 200, currency: "ZAR", rating: 4, comment: "Sharp line-up.", date: "2025-07-14" },
    { country: "Vietnam", city: "Hanoi", price: 150000, currency: "VND", rating: 5, comment: "Street barber. Authenticity 10/10.", date: "2025-12-10" },
    { country: "France", city: "Paris", price: 35, currency: "EUR", rating: 4, comment: "Very stylish, as expected.", date: "2025-10-25" },
    { country: "Mexico", city: "Mexico City", price: 250, currency: "MXN", rating: 5, comment: "Excellent service and shave.", date: "2025-06-18" },
    { country: "Canada", city: "Toronto", price: 40, currency: "CAD", rating: 3, comment: "Decent, but long wait time.", date: "2025-09-05" },
    { country: "Italy", city: "Rome", price: 20, currency: "EUR", rating: 4, comment: "Classic Italian barber experience.", date: "2025-11-12" },
    { country: "Spain", city: "Barcelona", price: 18, currency: "EUR", rating: 5, comment: "Modern shop, very professional.", date: "2025-12-20" },
    { country: "Turkey", city: "Istanbul", price: 300, currency: "TRY", rating: 5, comment: "The ear singeing was terrifying but the results are great!", date: "2025-08-10" },
    { country: "India", city: "Mumbai", price: 500, currency: "INR", rating: 5, comment: "Head massage included. Incredible value.", date: "2025-07-28" },
    { country: "Colombia", city: "Medellín", price: 35000, currency: "COP", rating: 4, comment: "Great skin fade.", date: "2025-05-30" },
    { country: "Portugal", city: "Lisbon", price: 15, currency: "EUR", rating: 4, comment: "Traditional shop near the center.", date: "2025-11-15" },
    { country: "Greece", city: "Athens", price: 12, currency: "EUR", rating: 3, comment: "Simple and effective.", date: "2025-09-22" },
    { country: "Argentina", city: "Buenos Aires", price: 5000, currency: "ARS", rating: 5, comment: "Passionate barbers, felt like family.", date: "2025-06-05" },
    { country: "UAE", city: "Dubai", price: 80, currency: "AED", rating: 4, comment: "Luxury experience but paid for it.", date: "2025-12-01" },
    { country: "Switzerland", city: "Zurich", price: 65, currency: "CHF", rating: 4, comment: "Pristine shop, very expensive.", date: "2025-10-10" },
    { country: "Morocco", city: "Marrakech", price: 50, currency: "MAD", rating: 5, comment: "Inside the Medina. Friendly and fast.", date: "2025-07-07" },
    { country: "South Korea", city: "Seoul", price: 25000, currency: "KRW", rating: 5, comment: "The precision is unmatched.", date: "2025-11-25" },
    { country: "Egypt", city: "Cairo", price: 100, currency: "EGP", rating: 4, comment: "Great experience in a busy district.", date: "2025-08-15" },
    { country: "Czech Republic", city: "Prague", price: 400, currency: "CZK", rating: 4, comment: "Nice hip spot in Vinohrady.", date: "2025-12-12" },
    { country: "Indonesia", city: "Bali", price: 100000, currency: "IDR", rating: 5, comment: "Best holiday haircut ever.", date: "2025-12-28" },
    { country: "Netherlands", city: "Amsterdam", price: 35, currency: "EUR", rating: 4, comment: "Cool interior, great music.", date: "2025-10-05" },
    { country: "Singapore", city: "Singapore", price: 15, currency: "SGD", rating: 4, comment: "Quick and efficient at a local mall.", date: "2025-11-08" },
    { country: "Sweden", city: "Stockholm", price: 450, currency: "SEK", rating: 4, comment: "Very clean Scandi style.", date: "2025-09-30" },
    { country: "Norway", city: "Oslo", price: 500, currency: "NOK", rating: 3, comment: "Pricey, but standard for Norway.", date: "2025-10-20" },
    { country: "Denmark", city: "Copenhagen", price: 350, currency: "DKK", rating: 4, comment: "Effortless cool vibe.", date: "2025-11-15" },
    { country: "Ireland", city: "Dublin", price: 25, currency: "EUR", rating: 4, comment: "Good craic and a good cut.", date: "2025-12-03" },
    { country: "Poland", city: "Warsaw", price: 80, currency: "PLN", rating: 5, comment: "Top quality for a great price.", date: "2025-08-25" },
    { country: "Hungary", city: "Budapest", price: 4000, currency: "HUF", rating: 4, comment: "Solid barbershop in the Jewish Quarter.", date: "2025-07-20" },
    { country: "Austria", city: "Vienna", price: 30, currency: "EUR", rating: 4, comment: "Elegant and professional.", date: "2025-09-10" },
    { country: "Belgium", city: "Brussels", price: 22, currency: "EUR", rating: 4, comment: "Quick walk-in.", date: "2025-11-01" },
    { country: "Israel", city: "Tel Aviv", price: 100, currency: "ILS", rating: 5, comment: "Very trendy and sharp.", date: "2025-10-18" },
    { country: "China", city: "Shanghai", price: 60, currency: "CNY", rating: 3, comment: "No-frills local spot.", date: "2025-08-30" },
    { country: "Malaysia", city: "Kuala Lumpur", price: 35, currency: "MYR", rating: 4, comment: "Great barber in Bukit Bintang.", date: "2025-11-10" },
    { country: "Philippines", city: "Manila", price: 300, currency: "PHP", rating: 5, comment: "High quality and very friendly.", date: "2025-12-15" },
    { country: "New Zealand", city: "Auckland", price: 45, currency: "NZD", rating: 4, comment: "Good service, solid fade.", date: "2025-12-05" },
    { country: "Chile", city: "Santiago", price: 12000, currency: "CLP", rating: 4, comment: "Fast and professional.", date: "2025-06-25" },
    { country: "Peru", city: "Lima", price: 40, currency: "PEN", rating: 4, comment: "Great value in Miraflores.", date: "2025-05-20" },
    { country: "Nigeria", city: "Lagos", price: 2500, currency: "NGN", rating: 5, comment: "Sharp line-up, very skilled.", date: "2025-07-10" },
    { country: "Kenya", city: "Nairobi", price: 800, currency: "KES", rating: 4, comment: "Friendly barber, great cut.", date: "2025-08-01" },
    { country: "Finland", city: "Helsinki", price: 40, currency: "EUR", rating: 4, comment: "Quiet and well done.", date: "2025-10-12" },
    { country: "Israel", city: "Jerusalem", price: 80, currency: "ILS", rating: 4, comment: "Historic feel in the shop.", date: "2025-09-05" },
    { country: "Jordan", city: "Amman", price: 10, currency: "JOD", rating: 5, comment: "Very hospitable and precise.", date: "2025-11-20" },
    { country: "Cambodia", city: "Siem Reap", price: 5, currency: "USD", rating: 5, comment: "Simple shop, great results.", date: "2025-12-25" }
];
